### ISSUE TITLE
Error Loading python27.dll Error Code 14001

### ISSUE THREAD

**Issue by piotrec** [Blue9/AudioJack-GUI#1]
When running AudioJack.exe following error pops up.

Error Loading Python DLL C:/Program Files/(x86)\AudioJack\python27.dll (error code 14001)

Running windows 7 64bit

**Comment by elcorders** [comment]
Do you have Visual Studio installed. same problem happened with me sometime back

[Update the redidis.](https://www.microsoft.com/en-us/download/details.aspx?id=26368)

**Comment by piotrec** [comment]
I have done the update with all 3 vcredist_x86.exe, vcredist_IA64.exe, vcredist_x64.exe. But this did not fix the error. I have even downloaded and installed Python. =(

**Comment by Blue9** [comment]
Currently, the executable file is only tested on Windows 10 64-bit. Other versions will be added soon.

**Comment by bibbca** [comment]
I found that if I uninstalled v0.3.0 and installed v0.2.0 and then reinstalled v0.3.0 The issue resolved itself.

**Comment by bibbca** [comment]
That fix no longer works.

**Comment by Blue9** [comment]
Try running from the source (i.e. using Python); that should cause no problems. Meanwhile, I will search for a fix to the issue you are having.

**Comment by Blue9** [comment]
Closing as release v0.3.0 is outdated.
