### ISSUE TITLE
Problem running in Python

### ISSUE THREAD

**Issue by Inferiex** [Blue9/AudioJack-GUI#12]
I read there are issues when running Audiojack on Windows 7 instead of windows 10. When I follow the steps to run it in cmd, I'm getting this error:

Traceback <most recent call last>:
File "audiojack_gui.py", line 3, in <module>
import Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by Blue9** [comment]
It looks like you are running Python 3 on your machine instead of Python 2. Python 3 is not backwards compatible with Python 2, so you need to install Python 2 separately to run the program.
