### ISSUE TITLE
Downloads to wrong folder, and can't tab to next line for manual entries

### ISSUE THREAD

**Issue by Chungbucket** [Blue9/AudioJack-GUI#13]
The files get added to the wrong downloads folder (ie wrong drive). Possible to change?

Also when manually entering music information, hitting tab doesn't make it go to the following line.

**Comment by Blue9** [comment]
Which folder does the file get downloaded to? You can use the settings to change the download folder. I will work on adding keyboard shortcuts to switch inputs.

**Comment by Blue9** [comment]
Tabs should be working for manual entries. The download path should be fixed now.
