### ISSUE TITLE
ffprobe not found

### ISSUE THREAD

**Issue by TedCruzUsername** [Blue9/AudioJack-GUI#14]
I tried downloading a file and received this error:

> DownloadError: ERROR: ffprobe or avprobe not found. Please install one.

I've already download ffmpeg (and the two accompanying files) and placed it in the same folder as the Audiojack files.

Help would be appreciated. Thanks in advance!

**Comment by Blue9** [comment]
Which OS are you running? Also, what output do you get when you type `ffmpeg -version` into your terminal?

**Comment by TedCruzUsername** [comment]
I believe I have version 3.2.2 of ffmpeg. It's worth mentioning, however, that I typed in ffmpeg -version into Terminal and it said that the file wasn't found so I just opened up ffmpeg and found the version that way.

As for my OS, I'm running MacOS Sierra. In particular, it's version 10.12.2.

**Comment by Blue9** [comment]
This looks like an issue with the way macOS handles executable files. Follow [this guide](http://ericholsinger.com/general/install-ffmpeg-on-a-mac/) and see if it fixes your problem.
