### ISSUE TITLE
After getting song metadata, nothing happens

### ISSUE THREAD

**Issue by Zefty** [Blue9/AudioJack-GUI#16]
[youtube] kwW0IAkwIWc: Downloading webpage
[youtube] kwW0IAkwIWc: Downloading video info webpage
[youtube] kwW0IAkwIWc: Extracting video information
Getting song metadata - this may take a while...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Wu\Desktop\AudioJack-GUI-0.3.0\audiojack_gui_v2.py", line 153, in get_results
    image_data = Image.open(StringIO(audiojack.get_cover_art_as_data(results[i][3]).decode('base64')))
KeyError: 3

That is from the command line and the gui just keep having green bar going left to right and nothing else appears even after minutes

**Comment by Blue9** [comment]
You should be running the current source code, not the source code posted in the outdated release. Follow the [guide](https://github.com/Blue9/AudioJack-GUI#step-by-step-guide) to get the program running.
