### ISSUE TITLE
Album art wont change

### ISSUE THREAD

**Issue by MikePerreman** [Blue9/AudioJack-GUI#17]
so, im running it as source in pyCharm, and it worked fine for the first song, but the album art never changed, even after manually selecting and a reboot

**Comment by Blue9** [comment]
What OS and Python version are you running? Also, what do you mean by "the album art never changed"? Did you run into the same problem when running from the command line? I ran the program with several different songs and ran into no issues.

**Comment by Blue9** [comment]
Closing as this is not a reproducible error.
