### ISSUE TITLE
error audiojack.py Ubuntu 16.04

### ISSUE THREAD

**Issue by freke70** [Blue9/AudioJack-GUI#19]
Hi, 

Sorry, I got another error.
Not sure if I'm doing something wrong.

Thanks,

Niels

/Downloads/AudioJack$ sudo python audiojack_gui.py
Traceback (most recent call last):
  File "audiojack_gui.py", line 22, in <module>
    import audiojack
  File "/home/username/Downloads/AudioJack/audiojack.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by Blue9** [comment]
I've updated [AudioJack](https://github.com/Blue9/AudioJack). Redownload `audiojack.py` and your problem should be fixed.
