### ISSUE TITLE
FeatureRequest: WebUI

### ISSUE THREAD

**Issue by CaptInsano** [Blue9/AudioJack-GUI#21]
Any chance of turning this into a WebApp for selfhosting on headless machines instead of a desktop app? I would love to run it on my RaspberryPi or in a Docker Container

I see mention of "Web version (Caution: Beta)" here: https://github.com/Blue9/AudioJack  but the link just brings me back to the desktop app github.

Thanks and congrats on a great project!

**Comment by Blue9** [comment]
The web version used to exist but I took it down to focus on the desktop app's features. I may release a new web version sometime in the future, but I cannot say for sure. Regardless, it should not be too difficult to build a web app yourself using a framework such as Flask or Django.
