### ISSUE TITLE
ffmpeg not installed error

### ISSUE THREAD

**Issue by 95nray** [Blue9/AudioJack-GUI#22]
Hello, 
First thanks for creating this, it is a very nice program with a great UI and is very easy to use (at least what I've gotten through thus far). 

I'm getting an error that I can not find mentioned on any of your pages related to this program, on AudioJack after selecting then album and metadata to add to the file, and it states "Error: ffmpeg is not installed. " In my command prompt I'm also recieving "ERROR: ffprobe or avprobe not found. Please install one." 

I have checked and I have .c and .h files for mpeg, and a .c for probe. Below is a screenshot of my working directory for further analysis, if you could point me in the right direction of what is wrong I'd really appreciate it so I can get to using the full program, thanks for your help in advance!

![image](https://cloud.githubusercontent.com/assets/15313475/23669243/0fbde1e6-0329-11e7-83c8-2118cecfc896.png)

**Comment by Blue9** [comment]
You should be using the executable builds of ffmpeg, which can be found [here](https://ffmpeg.zeranoe.com/builds/).
