### ISSUE TITLE
'python' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Zefty** [Blue9/AudioJack-GUI#24]
C:\Windows\system32>python audiojack_gui.py
'python' is not recognized as an internal or external command,
operable program or batch file.

After this i copied all the files to python27 folder in C:

C:\Python27>python audiojack_gui.py
Traceback (most recent call last):
  File "audiojack_gui.py", line 475, in <module>
    app = AudioJackGUI(root)
  File "audiojack_gui.py", line 92, in __init__
    if self.config.getboolean('main', 'auto_cb_grab'):
  File "C:\Python27\lib\ConfigParser.py", line 362, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: 1
1

then i get that. Btw audiojack used to work until i redownloaded. Thanks for this great app!

**Comment by Zefty** [comment]
I reinstalled everything including python now the gui loads but it goes to not responding when i hit "go" gets stuck on "[youtube] bzehQ60b3XI: Extracting video information" and screen freezes not responding

**Comment by Blue9** [comment]
To resolve the first error ('python' is not recognized as an internal or external command), paste the following in your command prompt:

    setx PATH "%PATH%;C:\Python27"

As to the second error (ValueError: Not a boolean: 1), delete the `settings.ini` file and restart the program.

To fix the third error (Stuck on "Extracting video information"), try updating `youtube-dl` by pasting the following in your command prompt:

    pip install -U youtube_dl
Old versions of `youtube-dl` break easily due to YouTube's updates, so I suggest updating `youtube-dl` every week or so.

**Comment by Zefty** [comment]
It still seems to get stuck at "[youtube] J0U4hF177Mg: Extracting video information" even after updating youtube_dl

Edit: kept trying and now it get stuck at "[youtube] J0U4hF177Mg: Downloading MPD manifest" then freezes and ram usage skyrockets. Could it be new version of youtube_dl being broken???

Edit2: Tried downloading the youtube-dl.exe file and downloading video and works so idk why audiojack with youtube dl is not working and freezing/not responding

**Comment by Blue9** [comment]
What happens if you let the program run for a while? AudioJack has to retrieve music metadata from MusicBrainz after downloading the video information and that can take some time.

**Comment by Zefty** [comment]
If i leave it to run, the computer lags/freezes and ram usage goes really high. 
I've tried uninstalling all modules and reinstalling them but no luck. Would you by any chance have older versions of audiojack i could use?

http://imgur.com/a/QTDwo


[youtube] J0U4hF177Mg: Downloading webpage
[youtube] J0U4hF177Mg: Downloading video info webpage
[youtube] J0U4hF177Mg: Extracting video information
[youtube] J0U4hF177Mg: Downloading MPD manifest
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Wu\Desktop\Audiojack 0.4.0\audiojack_gui.py", line 192, in get_results
    results = self.audiojack.get_results(input)[:8]
  File "C:\Users\Wu\Desktop\Audiojack 0.4.0\audiojack.py", line 37, in get_results
    return self._get_metadata(self._parse(info))
  File "C:\Users\Wu\Desktop\Audiojack 0.4.0\audiojack.py", line 111, in _parse
    video_title = re.sub(self._gen_regex(banned_words), ' ', video_title).strip()  # Remove banned words
  File "C:\Python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
MemoryError

**Comment by Zefty** [comment]
Finally I fixed it! I used python version 2.7.13 and it worked.
