### ISSUE TITLE
No option to download when it says "no results found" 

### ISSUE THREAD

**Issue by Zefty** [Blue9/AudioJack-GUI#27]
Hi, in a previous version (0.4.0) of Audiojack we had the option to select our own cover art or just download the file if there wasn't any available cover art. In the newest version when it says "no results found" there isn't an option to continue. Is there an upcoming fix for this?

**Comment by Blue9** [comment]
See 86af3fd. I will add the ability to set custom cover art in the near future.

**Comment by Zefty** [comment]
Thanks for your great project! Keep it up!
