### ISSUE TITLE
Can't Download Audio

### ISSUE THREAD

**Issue by danielfrier** [Blue9/AudioJack-GUI#29]
I get this error when I try to download 

[youtube] I7nxmGSWaz8: Downloading webpage
'LogFile' object has no attribute 'isatty'
Notified current thread

And it says 'An Unknown Error Occurred"

**Comment by Blue9** [comment]
Unfortunately, the LogFile error message is a result of a limitation in Kivy 1.9.1. Update Kivy to the latest version using `pip install -U kivy` and you'll see a more descriptive error message.
