### ISSUE TITLE
Stuck at loading screen.

### ISSUE THREAD

**Issue by Anvesh-Chennupati** [Blue9/AudioJack-GUI#7]
Installed it. 
When I run the application and paste the youtube url, its stuck in the loading screen. How can i fix it.

**Comment by Blue9** [comment]
It is not clear what is causing this issue. I would just suggest running `audiojack_gui.py` directly (there are instructions in the README on how to do this). From there, if you run into any errors, paste the terminal output here and I will look into the issue.

**Comment by Anvesh-Chennupati** [comment]
Yeah will do that

**Comment by Blue9** [comment]
Closing as release v0.3.0 is outdated.
