### ISSUE TITLE
ImportError: No module name PIL

### ISSUE THREAD

**Issue by michaeldchin** [Blue9/AudioJack-GUI#9]
I followed the install instructions and am getting this error on the final step when I do `python audiojack_gui.py`

```
Traceback (most recent call last):
  File "audiojack_gui.py", line 16, in <module>
    from PIL import Image, ImageTk
ImportError: No module named PIL
```

I'm running on Windows 10 with Python 2.7.12.

**Comment by Blue9** [comment]
Accidentally left out a dependency in the instructions. Do `pip install Pillow` and the issue should be fixed.

**Comment by michaeldchin** [comment]
Alright that worked. Got another error after that about an icon not being defined. The guide doesn't explicitly mention the icon, but I just grabbed the icon from the repo, it works now. Thanks!
